-- workshop05_1
-- DDL

-- 29. 계열 정보를 저장할 카테고리 테이블을 작성
CREATE TABLE TB_CATEGORY
( NAME VARCHAR2(10),
  USE_YN CHAR(1) DEFAULT 'Y' );

-- 30. 과목 구분을 저장할 테이블을 작성
CREATE TABLE TB_CLASS_TYPE
( NO VARCHAR2(5) CONSTRAINT TB_CLASS_TYPE_NO_PK PRIMARY KEY, 
  NAME VARCHAR2(10) );

-- 31. TB_CATAGORY 테이블의 NAME 컬럼에 PRIMARY KEY를 생성 (KEY 이름을 생성하지 않아도 무방)
ALTER TABLE TB_CATEGORY
ADD CONSTRAINT TB_CATEGORY_NAME_PK PRIMARY KEY(NAME);

-- 32. TB_CLASS_TYPE 테이블의 NAME 컬럼에 NULL 값이 들어가지 않도록 속성을 변경
ALTER TABLE TB_CLASS_TYPE
MODIFY ( NAME VARCHAR2(10) CONSTRAINT TB_CLASS_TYPE_NAME_NN NOT NULL );
--MODIFY ( NAME NOT NULL );

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('TB_CLASS_TYPE'); -- NOT NULL의 CONSTRAINT_TYPE : C

-- 33. 두 테이블에서 컬럼 명이 NO인 것은 기존 타입을 유지하면서 크기는 10 으로, 
--     컬럼명이 NAME 인 것은 마찬가지로 기존 타입을 유지하면서 크기 20 으로 변경
ALTER TABLE TB_CATEGORY
MODIFY ( NAME VARCHAR2(20) );

ALTER TABLE TB_CLASS_TYPE
MODIFY ( NO VARCHAR2(10),
         NAME VARCHAR2(20) );



DESC TB_CATEGORY;
DESC TB_CLASS_TYPE;

SELECT * FROM TB_CATEGORY;
SELECT * FROM TB_CLASS_TYPE;
